#!/bin/bash
#UNCOMMENT NEXT LINE
cd $(dirname $0)
#IF YOU INSTALLED ELASTICSEARCH THROUGHT BREW UNCOMMENT NEXT LINE:
brew services start elasticsearch
#IF YOU INSTALLED ELASTICSEARCH IN ANOTHER DIR UNCOMMENT NEXT LINE AND REPLACE ‘PATH’ WITH THE CORRECT ELASTICSEARCH'S PATH
#./PATH/bin/elasticsearch
#UNCOMMENT NEXT LINE
sleep 15
#UNCOMMENT NEXT LINE
node index.js & open -a "Google Chrome" --args --kiosk --app=http://localhost:3000
#UNCOMMENT NEXT LINE
node index.js
# USE THE COMMAND LINE TO MOVE INTO THE DIRECTORY THAT CONTAINS THIS FILE AND TYPE NEXT LINE IN YOUR TERMINAL TO MAKE IT EXECUTABLE:
#chmod +x start_audioguide.sh t
