#!/bin/bash
#UNCOMMENT NEXT LINE
#IF YOU INSTALLED ELASTICSEARCH THROUGHT BREW UNCOMMENT NEXT ROW:
#brew services stop elasticsearch
#IF YOU INSTALLED ELASTICSEARCH IN ANOTHER DIR UNCOMMENT NEXT ROW:
pkill -f elasticsearch
#UNCOMMENT NEXT LINE
pkill -f node
#IF YOU PREFER, USE THE COMMAND LINE TO MOVE INTO THE DIRECTORY THAT CONTAINS THIS FILE AND TYPE NEXT LINE IN YOUR TERMINAL 
#chmod +x execute_audioguide.sh

